name: StatusMoarFediverse

on:

  schedule:
    - cron: 0 0 * * *'
  workflow_dispatch:

jobs:
  status:
    runs-on: ubuntu-latest
    steps: 
      - name: Graphana call
        run: | 
          curl "https://fakerelay.gervas.io/index-posts-count?period=24h" -H 'Authorization: Bearer ${{secrets.FAKERELAY_APIKEY}}'
